add mocks and states
htmlacademy-react/2073413-six-cities-10 pull request #5
Opened 2022-07-24 16:43 UTC by lookinsidethebox

2022-07-26 04:44 UTC, Dima-Dim requested changes

2022-07-26 04:44 UTC, Dima-Dim commented on project/src/components/card-list/card-list.tsx
> +  const [activeCardId, setActiveCardId] = React.useState<number>();
Почему не сделать это в MainCard?

2022-07-26 04:44 UTC, Dima-Dim commented on project/src/pages/favorites-screen/favorites-screen.tsx
> +  list.forEach((item) => {
Почему не использовать метод map или filter на list-е?

2022-07-26 04:44 UTC, Dima-Dim commented on project/src/pages/favorites-screen/favorites-screen.tsx
> +              groupByCity(favorites).map((val) => (
Вместо val лучше использовать более осознаное именование.

2022-07-26 04:44 UTC, Dima-Dim commented on project/src/pages/property-not-logged-screen/property-not-logged-screen.tsx
> +  return offers.find((x) => x.id === Number(id)) ?? null;
Тоже что зна x?

2022-07-26 04:44 UTC, Dima-Dim commented on project/src/pages/property-not-logged-screen/property-not-logged-screen.tsx
> +  } else {
Если выше есть ruturn, зачем else?

2022-07-26 04:44 UTC, Dima-Dim commented on project/src/pages/property-not-logged-screen/property-not-logged-screen.tsx
> +                offers.slice(0, 3).map((card) => (
Что за магическое число 3?

2022-07-26 04:44 UTC, Dima-Dim commented on project/src/pages/property-screen/property-screen.tsx
> +                offers.slice(0, 3).map((card) => (
Где-то это я уже видел :) И не только это.

2022-07-26 12:06 UTC, lookinsidethebox commented on project/src/components/card-list/card-list.tsx
> +  const [activeCardId, setActiveCardId] = React.useState<number>();
Изначально так и было, но в задании сказано, что должен быть новый компонент  «Список предложений», поэтому пришлось его добавить. Возможно, для того, чтобы конкретно на него навешивать state с активной карточкой, а не на весь MainScreen.

2022-07-26 12:12 UTC, lookinsidethebox commented on project/src/pages/favorites-screen/favorites-screen.tsx
> +  list.forEach((item) => {
А разве map и filter не должны результатом вернуть мне новый массив? Он мне по сути ни к чему - я просто перебираю все элементы в list и заполняю свой Map<string, PropertyType[]>, т.к. мне нужно сгруппировать список по городам.

2022-07-27 06:20 UTC, Dima-Dim commented on project/src/components/card-list/card-list.tsx
> +  const [activeCardId, setActiveCardId] = React.useState<number>();
Судя по твоему комментария, разместить здесь `React.useState` это всё же твоё решение :) а не чьё либо требование.

2022-07-27 06:22 UTC, Dima-Dim commented on project/src/pages/favorites-screen/favorites-screen.tsx
> +  list.forEach((item) => {
`Он мне по сути ни к чему` и `заполняю свой Map`. Если новый массив тебе ни к чему, то и Map тогда ни к чему. Иначе какое-то противоречие :)
На самом деле твой вариант просто сложнее.

2022-07-28 06:27 UTC, merged