Module6 task2
htmlacademy-react/2073413-six-cities-10 pull request #9
Opened 2022-08-09 17:33 UTC by lookinsidethebox

2022-08-10 17:15 UTC, Dima-Dim requested changes

2022-08-10 17:15 UTC, Dima-Dim commented on project/src/store/reducer.ts
> +const DEFAULT_CITY = getDefaultCity();
Это не константы, потому что значения этих переменных не статичны и зависят от выполнения функций.

2022-08-10 17:15 UTC, Dima-Dim commented on project/src/hooks/index.ts
> +export const getDefaultCity = () => cities.Paris;
Зачем это делать функцией? Не проще просто завести переменную в которой будет хранится дефолтовое значение?

2022-08-10 17:15 UTC, Dima-Dim commented on project/src/hooks/index.ts
> +export const getDefaultSortId = () => DEFAULT_SORT;
Тоже не понятно для чего тут функция,

2022-08-10 17:15 UTC, Dima-Dim commented on project/src/hooks/index.ts
> +export const getSortById = (id: number) => sorts.filter((sort) => sort.id === id)[0];
Очень опасная функция получилась. `getSortById` - название не отражает что именно сортируется. Внутри же используется метод не сортировки, а фильтрации, тоже сбивает с толку. В функцию не передаётся то, что сортируется, из-за этого она слабо управляемая. Так лучше не делать.
Всё это лежит в папке hooks, но где тут хуки?

2022-08-10 17:15 UTC, Dima-Dim commented on project/src/hooks/index.ts
> +export function getOffersByCity (id: number, sort: number) {
Если sort это number, то сюда может прийти и 5. Что в этом случаем мы получим? И можем ли мы сюда передавать 5?

2022-08-10 17:15 UTC, Dima-Dim commented on project/src/store/reducer.ts
> +      state.sort = getSortById(action.payload);
Что в итоге мы хотим хранить в поле sort? Из типизации это не понятно.

2022-08-11 15:13 UTC, lookinsidethebox commented on project/src/store/reducer.ts
> +const DEFAULT_CITY = getDefaultCity();
![image](https://user-images.githubusercontent.com/23139671/184167683-ef8719f8-7864-4907-a283-8909618b363a.png)

Линтер считает иначе(

2022-08-11 15:30 UTC, lookinsidethebox commented on project/src/store/reducer.ts
> +      state.sort = getSortById(action.payload);
Переименовала Sort в SortType везде, чтобы было понятно - это сущность, обозначающая тип сортировки (по популярным, по цене и т.п.). Непосредственно сама сортировка происходит при получении офферов - офферы записываются в store сразу в отсортированном виде.

2022-08-11 15:53 UTC, lookinsidethebox commented on project/src/hooks/index.ts
> +export function getOffersByCity (id: number, sort: number) {
Если придет 5, то вернется неотсортированный список, как в случае, если придет 1 и другие значения, кроме 2, 3 и 4.

2022-08-12 12:30 UTC, Dima-Dim commented on project/src/store/reducer.ts
> +const DEFAULT_CITY = getDefaultCity();
Я не про let, а про название большими буквами.

2022-08-15 03:26 UTC, merged